GRANT EXECUTE ON PROCEDURE datasikkerhet_prosjekt.AnswerAQuestionLecturer TO 'foreleser'@'localhost', 'softsec'@'localhost';
GRANT EXECUTE ON PROCEDURE datasikkerhet_prosjekt.ChangePasswordOfAUser TO 'foreleser'@'localhost', 'student'@'localhost', 'softsec'@'localhost';
GRANT EXECUTE ON PROCEDURE datasikkerhet_prosjekt.CommentOnQuestionAsGuest TO 'guest'@'localhost', 'softsec'@'localhost';
GRANT EXECUTE ON PROCEDURE datasikkerhet_prosjekt.CommitApprovalOfLecturerRequest TO 'softsec'@'localhost';
GRANT EXECUTE ON PROCEDURE datasikkerhet_prosjekt.DeleteAMessageAdmin TO 'softsec'@'localhost';
GRANT EXECUTE ON PROCEDURE datasikkerhet_prosjekt.DeleteAUserAdmin TO 'softsec'@'localhost';
GRANT EXECUTE ON PROCEDURE datasikkerhet_prosjekt.DoesEmailExistInDb TO 'guest'@'localhost', 'softsec'@'localhost';
GRANT EXECUTE ON PROCEDURE datasikkerhet_prosjekt.GetAllLecturerRequests TO 'softsec'@'localhost';
GRANT EXECUTE ON PROCEDURE datasikkerhet_prosjekt.GetAllMessagesWithLecturerPictureAdmin TO 'softsec'@'localhost';
GRANT EXECUTE ON PROCEDURE datasikkerhet_prosjekt.GetAllQuestionsForSubjectLecturer TO 'foreleser'@'localhost', 'softsec'@'localhost';
GRANT EXECUTE ON PROCEDURE datasikkerhet_prosjekt.GetAllReportedMessagesAdmin TO 'softsec'@'localhost';
GRANT EXECUTE ON PROCEDURE datasikkerhet_prosjekt.GetAllSubjectCodesAndPins TO 'guest'@'localhost', 'softsec'@'localhost';
GRANT EXECUTE ON PROCEDURE datasikkerhet_prosjekt.GetAllUnansweredQuestionsForSubjectLecturer TO 'foreleser'@'localhost', 'softsec'@'localhost';
GRANT EXECUTE ON PROCEDURE datasikkerhet_prosjekt.GetAskedQuestionsApi TO 'student'@'localhost', 'softsec'@'localhost';
GRANT EXECUTE ON PROCEDURE datasikkerhet_prosjekt.GetEmailAndPassAllLecturers TO 'foreleser'@'localhost', 'softsec'@'localhost';
GRANT EXECUTE ON PROCEDURE datasikkerhet_prosjekt.GetEmailAndPassAllStudents TO 'student'@'localhost', 'softsec'@'localhost';
GRANT EXECUTE ON PROCEDURE datasikkerhet_prosjekt.GetEmailAndPassAllUsers TO 'softsec'@'localhost';
GRANT EXECUTE ON PROCEDURE datasikkerhet_prosjekt.GetInfoForLogginInAllUsers TO 'guest'@'localhost', 'softsec'@'localhost';
GRANT EXECUTE ON PROCEDURE datasikkerhet_prosjekt.GetMessageFeedStudent TO 'student'@'localhost', 'softsec'@'localhost';
GRANT EXECUTE ON PROCEDURE datasikkerhet_prosjekt.GetNameAndEmailOfAllStudentsAndLecturers TO 'softsec'@'localhost';
GRANT EXECUTE ON PROCEDURE datasikkerhet_prosjekt.GetNameAndEmailOfStudentOrLecturer TO 'softsec'@'localhost';
GRANT EXECUTE ON PROCEDURE datasikkerhet_prosjekt.GetPictureOfALecturer TO 'student'@'localhost', 'softsec'@'localhost';
GRANT EXECUTE ON PROCEDURE datasikkerhet_prosjekt.GetPictureOfEachLecturerOfEachSubject TO 'student'@'localhost', 'softsec'@'localhost';
GRANT EXECUTE ON PROCEDURE datasikkerhet_prosjekt.GuestFeedGetSubjectAndLecturer TO 'guest'@'localhost', 'softsec'@'localhost';
GRANT EXECUTE ON PROCEDURE datasikkerhet_prosjekt.IsSubjectTaken TO 'guest'@'localhost', 'softsec'@'localhost';
GRANT EXECUTE ON PROCEDURE datasikkerhet_prosjekt.LoginGetIdApi TO 'guest'@'localhost', 'softsec'@'localhost';
GRANT EXECUTE ON PROCEDURE datasikkerhet_prosjekt.LoginGetPassApi TO 'guest'@'localhost', 'softsec'@'localhost';
GRANT EXECUTE ON PROCEDURE datasikkerhet_prosjekt.RegisterNewUser TO 'guest'@'localhost', 'softsec'@'localhost';
GRANT EXECUTE ON PROCEDURE datasikkerhet_prosjekt.ReportAQuestionAsGuest TO 'guest'@'localhost', 'softsec'@'localhost';
GRANT EXECUTE ON PROCEDURE datasikkerhet_prosjekt.SendQuestionStudent TO 'student'@'localhost', 'softsec'@'localhost';
GRANT EXECUTE ON PROCEDURE datasikkerhet_prosjekt.SendQuestionStudentApi TO 'student'@'localhost', 'softsec'@'localhost';
GRANT EXECUTE ON PROCEDURE datasikkerhet_prosjekt.UpdateAUserAdmin TO 'softsec'@'localhost';
